main : com.clashwars.cwcore.CWCore
name: CWCore
version: 1.0
description: Core plugin.
softdepend: [Vault, ProtocolLib, WorldGuard, Essentials]
commands:
  cww:
    description: Get cuboid selection wand.
    usage: /<command>
    aliases: [cwwand, arw, arwand]
  sel:
    description: Cuboid selection editor commands.
    usage: /<command> [args]
  p1:
    description: Set cuboid pos 1.
    usage: /<command>
    aliases: [l1]
  p2:
    description: Set cuboid pos 2.
    usage: /<command>
    aliases: [l2]