main : com.clashwars.cwcore.CWCore
name: CWCore
version: 1.0
description: Core plugin.
softdepend: [Vault, ProtocolLib, WorldGuard, Factions, Essentials]
commands:
  cww:
    description: Get cuboid selection wand.
    usage: /<command>
    aliases: [cwwand, arw, arwand]
  sel:
    description: Cuboid selection editor commands.
    usage: /<command> [args]
  p1:
    description: Set cuboid pos 1.
    usage: /<command>
    aliases: [l1]
  p2:
    description: Set cuboid pos 2.
    usage: /<command>
    aliases: [l2]
  pe:
    description: Display particle effects
    usage: /<command>
  sound:
    description: Play sounds
    usage: /<command>
    aliases: [so]
  soundcheck:
    description: Test sounds with different pitches
    usage: /<command>
    aliases: [sc, soc]